#!/bin/bash
#SBATCH --job-name=fourier-iso          # create a short name for your job
#SBATCH --time=00:10:00          # total run time limit (HH:MM:SS)
#SBATCH --mem=48G
#SBATCH --mail-type=begin        # send mail when process begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu
#SBATCH --constraint=a100
#SBATCH --gres=gpu:1

module load anaconda3/2023.9
conda activate desc-env
export XLA_PYTHON_CLIENT_MEM_FRACTION=.93

jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace test.ipynb
