#!/bin/bash
#SBATCH --job-name=mpi7_bn
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=9          # MPI ranks per node
#SBATCH --cpus-per-task=9         # CPU cores per MPI rank
#SBATCH --mem=350G
#SBATCH --time=00:10:00
#SBATCH --output=mpi7.%j.out
#SBATCH --error=mpi7.%j.err
#SBATCH --mail-type=BEGIN,END,FAIL         # Notifications for job done & fail
#SBATCH --mail-user=fcastro@princeton.edu

# ---- Load modules ----
module purge
module load anaconda3/2025.6
module load openmpi/gcc/4.1.6

# ---- Activate environment ----
source activate desc-ray

# ---- CPU-only configuration ----
#export OMP_NUM_THREADS=1
#export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK
export JAX_PLATFORMS=cpu

# ---- Python script to run ----
PYTHON_SCRIPT="mpi6.py"    # replace with your notebook-converted Python script

which mpirun

# ---- Run MPI job ----
if [ -f "$PYTHON_SCRIPT" ]; then
    echo "Running Python script $PYTHON_SCRIPT with $SLURM_NTASKS MPI ranks..."
   srun -n $SLURM_NTASKS python "$PYTHON_SCRIPT"
else
    echo "Error: Python script $PYTHON_SCRIPT not found."
fi

echo "Job finished."
