#!/bin/bash
#SBATCH --job-name=pinv_cpu_job
#SBATCH --time=02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=180
#SBATCH --mem=300G
#SBATCH --mail-type=begin        # send mail when process begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu

# Load your modules or activate your environment
module purge
module load anaconda3/2023.9
source activate desc-env  # Replace with your actual env name

# Optional: Set JAX to prefer CPU explicitly
export XLA_PYTHON_CLIENT_PREALLOCATE=false
export XLA_FLAGS=--xla_force_host_platform_device_count=128

# Run your script
#python jnpinv.py
jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace jnpinv.ipynb
