#!/bin/bash
#SBATCH --job-name=30sQA          # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=8        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=8G         # memory per cpu-core (4G is default)
#SBATCH --time=00:10:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=begin        # send mail when process begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu
#SBATCH --constraint=gpu80
#SBATCH --gres=gpu:1

module load anaconda3/2023.9
conda activate desc-env

export XLA_PYTHON_CLIENT_MEM_FRACTION=.93

jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace direct.ipynb
