comment:                  # this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: true        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  after_n_builds: 10
coverage:
  status:
    patch:
      default:
        informational: false
    project:
      default:
        informational: false
        threshold: 2.0
github_checks:
  annotations: true
