comment:                  # this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: true        # [true :: must have a base report to post]
  require_head: true        # [true :: must have a head report to post]
  after_n_builds: 14   # wait for 8 unit and 6 regression tests to complete
coverage:
  status:
    patch:
      default:
        informational: false
        if_not_found: success # for 'only-docs-comments' labeled PRs
    project:
      default:
        informational: false
        threshold: 2.0
        if_not_found: success # for 'only-docs-comments' labeled PRs
github_checks:
  annotations: true
