#!/bin/bash
#SBATCH --job-name=rd_RQA
#SBATCH --time=00:01:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1
#SBATCH --mem=128G  # Per node
#SBATCH --mail-type=begin        # send mail when process begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu
#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err

# Load your modules or activate your environment
# module purge
module load anaconda3/2024.6
source activate desc-mpi  # Replace with your actual env name

# Optional: Set JAX to prefer CPU explicitly
export XLA_PYTHON_CLIENT_PREALLOCATE=false
export XLA_FLAGS=--xla_force_host_platform_device_count=16
export OMP_NUM_THREADS=8
export MKL_NUM_THREADS=8

# Run notebook with srun for MPI coordination
#srun --nodes=2 --ntasks=16 python -m jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace direct-reg.ipynb
srun --nodes=2 --ntasks=16 python -m direct-reg.py
