#!/bin/bash
#SBATCH --job-name=rd_RQA
#SBATCH --time=00:01:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --mail-type=begin        # send mail when process begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu

# Load your modules or activate your environment
# module purge
module load anaconda3/2024.6
source activate desc-env  # Replace with your actual env name

# Optional: Set JAX to prefer CPU explicitly
export XLA_PYTHON_CLIENT_PREALLOCATE=false
export XLA_FLAGS=--xla_force_host_platform_device_count=32

# Run your script
#python run_pinv.py
jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace direct.ipynb
