#!/bin/bash
#SBATCH --job-name=R_Opt7         # create a short name for your job
#SBATCH --time=01:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu
#SBATCH --constraint=a100
#SBATCH --gres=gpu:1

module load anaconda3/2023.9
conda activate desc-env

jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace breg.ipynb
