"""data_index containts all of the quantities calculated by the compute functions.

label = (str) title of the quantity in LaTeX format
units = (str) units of the quantity in LaTeX format
fun = (str) function name in compute_funs.py that computes the quantity
dim = (int) dimension of the quantity: 0-D, 1-D, or 3-D
"""

data_index = {
    # toroidal flux
    "psi": {
        "label": "\\Psi \\ 2 \\pi",
        "units": "Wb",
        "fun": "compute_toroidal_flux",
        "dim": 1,
    },
    "psi_r": {
        "label": "\\Psi' \\ 2 \\pi",
        "units": "Wb",
        "fun": "compute_toroidal_flux",
        "dim": 1,
    },
    "psi_rr": {
        "label": "\\Psi'' \\ 2 \\pi",
        "units": "Wb",
        "fun": "compute_toroidal_flux",
        "dim": 1,
    },
    # pressure
    "p": {
        "label": "p",
        "units": "Pa",
        "fun": "compute_pressure",
        "dim": 1,
    },
    "p_r": {
        "label": "\\partial_{\\rho} p",
        "units": "Pa",
        "fun": "compute_pressure",
        "dim": 1,
    },
    # rotational transform
    "iota": {
        "label": "\\iota",
        "units": "",
        "fun": "compute_rotational_transform",
        "dim": 1,
    },
    "iota_r": {
        "label": "\\partial_{\\rho} \\iota",
        "units": "",
        "fun": "compute_rotational_transform",
        "dim": 1,
    },
    "iota_rr": {
        "label": "\\partial_{\\rho\\rho} \\iota",
        "units": "",
        "fun": "compute_rotational_transform",
        "dim": 1,
    },
    # R
    "R": {
        "label": "R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 0, 0]],
    },
    "R_r": {
        "label": "\\partial_{\\rho} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[1, 0, 0]],
    },
    "R_t": {
        "label": "\\partial_{\\theta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 1, 0]],
    },
    "R_z": {
        "label": "\\partial_{\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 0, 1]],
    },
    "R_rr": {
        "label": "\\partial_{\\rho\\rho} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[2, 0, 0]],
    },
    "R_tt": {
        "label": "\\partial_{\\theta\\theta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 2, 0]],
    },
    "R_zz": {
        "label": "\\partial_{\\zeta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 0, 2]],
    },
    "R_rt": {
        "label": "\\partial_{\\rho\\theta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[1, 1, 0]],
    },
    "R_rz": {
        "label": "\\partial_{\\rho\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[1, 0, 1]],
    },
    "R_tz": {
        "label": "\\partial_{\\theta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 1, 1]],
    },
    "R_rrr": {
        "label": "\\partial_{\\rho\\rho\\rho} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[3, 0, 0]],
    },
    "R_ttt": {
        "label": "\\partial_{\\theta\\theta\\theta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 3, 0]],
    },
    "R_zzz": {
        "label": "\\partial_{\\zeta\\zeta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 0, 3]],
    },
    "R_rrt": {
        "label": "\\partial_{\\rho\\rho\\theta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[2, 1, 0]],
    },
    "R_rtt": {
        "label": "\\partial_{\\rho\\theta\\theta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[1, 2, 0]],
    },
    "R_rrz": {
        "label": "\\partial_{\\rho\\rho\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[2, 0, 1]],
    },
    "R_rzz": {
        "label": "\\partial_{\\rho\\zeta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[1, 0, 2]],
    },
    "R_ttz": {
        "label": "\\partial_{\\theta\\theta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 2, 1]],
    },
    "R_tzz": {
        "label": "\\partial_{\\theta\\zeta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[0, 1, 2]],
    },
    "R_rtz": {
        "label": "\\partial_{\\rho\\theta\\zeta} R",
        "units": "m",
        "fun": "compute_R",
        "dim": 1,
        "R_derivs": [[1, 1, 1]],
    },
    # Z
    "Z": {
        "label": "Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 0, 0]],
    },
    "Z_r": {
        "label": "\\partial_{\\rho} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[1, 0, 0]],
    },
    "Z_t": {
        "label": "\\partial_{\\theta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 1, 0]],
    },
    "Z_z": {
        "label": "\\partial_{\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 0, 1]],
    },
    "Z_rr": {
        "label": "\\partial_{\\rho\\rho} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[2, 0, 0]],
    },
    "Z_tt": {
        "label": "\\partial_{\\theta\\theta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 2, 0]],
    },
    "Z_zz": {
        "label": "\\partial_{\\zeta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 0, 2]],
    },
    "Z_rt": {
        "label": "\\partial_{\\rho\\theta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[1, 1, 0]],
    },
    "Z_rz": {
        "label": "\\partial_{\\rho\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[1, 0, 1]],
    },
    "Z_tz": {
        "label": "\\partial_{\\theta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 1, 1]],
    },
    "Z_rrr": {
        "label": "\\partial_{\\rho\\rho\\rho} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[3, 0, 0]],
    },
    "Z_ttt": {
        "label": "\\partial_{\\theta\\theta\\theta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 3, 0]],
    },
    "Z_zzz": {
        "label": "\\partial_{\\zeta\\zeta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 0, 3]],
    },
    "Z_rrt": {
        "label": "\\partial_{\\rho\\rho\\theta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[2, 1, 0]],
    },
    "Z_rtt": {
        "label": "\\partial_{\\rho\\theta\\theta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[1, 2, 0]],
    },
    "Z_rrz": {
        "label": "\\partial_{\\rho\\rho\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[2, 0, 1]],
    },
    "Z_rzz": {
        "label": "\\partial_{\\rho\\zeta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[1, 0, 2]],
    },
    "Z_ttz": {
        "label": "\\partial_{\\theta\\theta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 2, 1]],
    },
    "Z_tzz": {
        "label": "\\partial_{\\theta\\zeta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[0, 1, 2]],
    },
    "Z_rtz": {
        "label": "\\partial_{\\rho\\theta\\zeta} Z",
        "units": "m",
        "fun": "compute_Z",
        "dim": 1,
        "Z_derivs": [[1, 1, 1]],
    },
    # lambda
    "lambda": {
        "label": "\\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 0, 0]],
    },
    "lambda_r": {
        "label": "\\partial_{\\rho} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[1, 0, 0]],
    },
    "lambda_t": {
        "label": "\\partial_{\\theta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 1, 0]],
    },
    "lambda_z": {
        "label": "\\partial_{\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 0, 1]],
    },
    "lambda_rr": {
        "label": "\\partial_{\\rho\\rho} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[2, 0, 0]],
    },
    "lambda_tt": {
        "label": "\\partial_{\\theta\\theta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 2, 0]],
    },
    "lambda_zz": {
        "label": "\\partial_{\\zeta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 0, 2]],
    },
    "lambda_rt": {
        "label": "\\partial_{\\rho\\theta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[1, 1, 0]],
    },
    "lambda_rz": {
        "label": "\\partial_{\\rho\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[1, 0, 1]],
    },
    "lambda_tz": {
        "label": "\\partial_{\\theta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 1, 1]],
    },
    "lambda_rrr": {
        "label": "\\partial_{\\rho\\rho\\rho} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[3, 0, 0]],
    },
    "lambda_ttt": {
        "label": "\\partial_{\\theta\\theta\\theta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 3, 0]],
    },
    "lambda_zzz": {
        "label": "\\partial_{\\zeta\\zeta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 0, 3]],
    },
    "lambda_rrt": {
        "label": "\\partial_{\\rho\\rho\\theta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[2, 1, 0]],
    },
    "lambda_rtt": {
        "label": "\\partial_{\\rho\\theta\\theta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[1, 2, 0]],
    },
    "lambda_rrz": {
        "label": "\\partial_{\\rho\\rho\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[2, 0, 1]],
    },
    "lambda_rzz": {
        "label": "\\partial_{\\rho\\zeta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[1, 0, 2]],
    },
    "lambda_ttz": {
        "label": "\\partial_{\\theta\\theta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 2, 1]],
    },
    "lambda_tzz": {
        "label": "\\partial_{\\theta\\zeta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[0, 1, 2]],
    },
    "lambda_rtz": {
        "label": "\\partial_{\\rho\\theta\\zeta} \\lambda",
        "units": "",
        "fun": "compute_lambda",
        "dim": 1,
        "L_derivs": [[1, 1, 1]],
    },
    # cartesian coordinates
    "X": {
        "label": "R \\cos{\\phi}",
        "units": "m",
        "fun": "compute_cartesian_coords",
        "dim": 1,
        "R_derivs": [[0, 0, 0]],
    },
    "Y": {
        "label": "R \\sin{\\phi}",
        "units": "m",
        "fun": "compute_cartesian_coords",
        "dim": 1,
        "R_derivs": [[0, 0, 0]],
    },
    # covariant basis
    "e_rho": {
        "label": "\\mathbf{e}_{\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 0, 0]],
        "Z_derivs": [[1, 0, 0]],
    },
    "e_theta": {
        "label": "\\mathbf{e}_{\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 1, 0]],
        "Z_derivs": [[0, 1, 0]],
    },
    "e_zeta": {
        "label": "\\mathbf{e}_{\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 0, 0], [0, 0, 1]],
        "Z_derivs": [[0, 0, 1]],
    },
    "e_rho_r": {
        "label": "\\mathbf{e}_{\\rho\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[2, 0, 0]],
        "Z_derivs": [[2, 0, 0]],
    },
    "e_rho_t": {
        "label": "\\mathbf{e}_{\\rho\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 1, 0]],
        "Z_derivs": [[1, 1, 0]],
    },
    "e_rho_z": {
        "label": "\\mathbf{e}_{\\rho\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 0, 1]],
        "Z_derivs": [[1, 0, 1]],
    },
    "e_theta_r": {
        "label": "\\mathbf{e}_{\\theta\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 1, 0]],
        "Z_derivs": [[1, 1, 0]],
    },
    "e_theta_t": {
        "label": "\\mathbf{e}_{\\theta\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 2, 0]],
        "Z_derivs": [[0, 2, 0]],
    },
    "e_theta_z": {
        "label": "\\mathbf{e}_{\\theta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 1, 1]],
        "Z_derivs": [[0, 1, 1]],
    },
    "e_zeta_r": {
        "label": "\\mathbf{e}_{\\zeta\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 0, 0], [1, 0, 1]],
        "Z_derivs": [[1, 0, 1]],
    },
    "e_zeta_t": {
        "label": "\\mathbf{e}_{\\zeta\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 1, 0], [0, 1, 1]],
        "Z_derivs": [[0, 1, 1]],
    },
    "e_zeta_z": {
        "label": "\\mathbf{e}_{\\zeta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 0, 1], [0, 0, 2]],
        "Z_derivs": [[0, 0, 2]],
    },
    "e_rho_rr": {
        "label": "\\mathbf{e}_{\\rho\\rho\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[3, 0, 0]],
        "Z_derivs": [[3, 0, 0]],
    },
    "e_rho_tt": {
        "label": "\\mathbf{e}_{\\rho\\theta\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 2, 0]],
        "Z_derivs": [[1, 2, 0]],
    },
    "e_rho_zz": {
        "label": "\\mathbf{e}_{\\rho\\zeta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 0, 2]],
        "Z_derivs": [[1, 0, 2]],
    },
    "e_rho_rt": {
        "label": "\\mathbf{e}_{\\rho\\rho\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[2, 1, 0]],
        "Z_derivs": [[2, 1, 0]],
    },
    "e_rho_rz": {
        "label": "\\mathbf{e}_{\\rho\\rho\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[2, 1, 0]],
        "Z_derivs": [[2, 1, 0]],
    },
    "e_rho_tz": {
        "label": "\\mathbf{e}_{\\rho\\theta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 1, 1]],
        "Z_derivs": [[1, 1, 1]],
    },
    "e_theta_rr": {
        "label": "\\mathbf{e}_{\\theta\\rho\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[2, 1, 0]],
        "Z_derivs": [[2, 1, 0]],
    },
    "e_theta_tt": {
        "label": "\\mathbf{e}_{\\theta\\theta\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 3, 0]],
        "Z_derivs": [[0, 3, 0]],
    },
    "e_theta_zz": {
        "label": "\\mathbf{e}_{\\theta\\zeta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 1, 2]],
        "Z_derivs": [[0, 1, 2]],
    },
    "e_theta_rt": {
        "label": "\\mathbf{e}_{\\theta\\rho\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 2, 0]],
        "Z_derivs": [[1, 2, 0]],
    },
    "e_theta_rz": {
        "label": "\\mathbf{e}_{\\theta\\rho\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 1, 1]],
        "Z_derivs": [[1, 1, 1]],
    },
    "e_theta_tz": {
        "label": "\\mathbf{e}_{\\theta\\theta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 2, 1]],
        "Z_derivs": [[0, 2, 1]],
    },
    "e_zeta_rr": {
        "label": "\\mathbf{e}_{\\zeta\\rho\\rho}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[2, 0, 0], [2, 0, 1]],
        "Z_derivs": [[2, 0, 1]],
    },
    "e_zeta_tt": {
        "label": "\\mathbf{e}_{\\zeta\\theta\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 2, 0], [0, 2, 1]],
        "Z_derivs": [[0, 2, 1]],
    },
    "e_zeta_zz": {
        "label": "\\mathbf{e}_{\\zeta\\zeta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 0, 2], [0, 0, 3]],
        "Z_derivs": [[0, 0, 3]],
    },
    "e_zeta_rt": {
        "label": "\\mathbf{e}_{\\zeta\\rho\\theta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 1, 0], [1, 1, 1]],
        "Z_derivs": [[1, 1, 1]],
    },
    "e_zeta_rz": {
        "label": "\\mathbf{e}_{\\zeta\\rho\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[1, 0, 1], [1, 0, 2]],
        "Z_derivs": [[1, 0, 2]],
    },
    "e_zeta_tz": {
        "label": "\\mathbf{e}_{\\zeta\\theta\\zeta}",
        "units": "m",
        "fun": "compute_covariant_basis",
        "dim": 3,
        "R_derivs": [[0, 1, 1], [0, 1, 2]],
        "Z_derivs": [[0, 1, 2]],
    },
    # contravariant basis
    "e^rho": {
        "label": "\\mathbf{e}^{\\rho}",
        "units": "m^{-1}",
        "fun": "compute_contravariant_basis",
        "dim": 3,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "e^theta": {
        "label": "\\mathbf{e}^{\\theta}",
        "units": "m^{-1}",
        "fun": "compute_contravariant_basis",
        "dim": 3,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "e^zeta": {
        "label": "\\mathbf{e}^{\\zeta}",
        "units": "m^{-1}",
        "fun": "compute_contravariant_basis",
        "dim": 3,
        "R_derivs": [[0, 0, 0]],
        "Z_derivs": [[0, 0, 0]],
    },
    # Jacobian
    "sqrt(g)": {
        "label": "\\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "sqrt(g)_r": {
        "label": "\\partial_{\\rho} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
    },
    "sqrt(g)_t": {
        "label": "\\partial_{\\theta} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
    },
    "sqrt(g)_z": {
        "label": "\\partial_{\\zeta} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
    },
    "sqrt(g)_rr": {
        "label": "\\partial_{\\rho\\rho} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
            [3, 0, 0],
            [2, 1, 0],
            [2, 0, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
            [3, 0, 0],
            [2, 1, 0],
            [2, 0, 1],
        ],
    },
    "sqrt(g)_tt": {
        "label": "\\partial_{\\theta\\theta} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
    },
    "sqrt(g)_zz": {
        "label": "\\partial_{\\zeta\\zeta} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
    },
    "sqrt(g)_tz": {
        "label": "\\partial_{\\theta\\zeta} \\sqrt{g}",
        "units": "m^{3}",
        "fun": "compute_jacobian",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
    },
    # covariant metric coefficients
    "g_rr": {
        "label": "g_{\\rho\\rho}",
        "units": "m^{2}",
        "fun": "compute_covariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[1, 0, 0]],
        "Z_derivs": [[1, 0, 0]],
    },
    "g_tt": {
        "label": "g_{\\theta\\theta}",
        "units": "m^{2}",
        "fun": "compute_covariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 1, 0]],
        "Z_derivs": [[0, 1, 0]],
    },
    "g_zz": {
        "label": "g_{\\zeta\\zeta}",
        "units": "m^{2}",
        "fun": "compute_covariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [0, 0, 1]],
        "Z_derivs": [[0, 0, 1]],
    },
    "g_rt": {
        "label": "g_{\\rho\\theta}",
        "units": "m^{2}",
        "fun": "compute_covariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[1, 0, 0], [0, 1, 0]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0]],
    },
    "g_rz": {
        "label": "g_{\\rho\\zeta}",
        "units": "m^{2}",
        "fun": "compute_covariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[1, 0, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 0, 1]],
    },
    "g_tz": {
        "label": "g_{\\theta\\zeta}",
        "units": "m^{2}",
        "fun": "compute_covariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[0, 1, 0], [0, 0, 1]],
    },
    # contravariant metric coefficients
    "g^rr": {
        "label": "g^{\\rho\\rho}",
        "units": "m^{-2}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "g^tt": {
        "label": "g^{\\theta\\theta}",
        "units": "m^{-2}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "g^zz": {
        "label": "g^{\\zeta\\zeta}",
        "units": "m^{-2}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0]],
        "Z_derivs": [[0, 0, 0]],
    },
    "g^rt": {
        "label": "g^{\\rho\\theta}",
        "units": "m^{-2}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "g^rz": {
        "label": "g^{\\rho\\zeta}",
        "units": "m^{-2}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "g^tz": {
        "label": "g^{\\theta\\zeta}",
        "units": "m^{-2}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "|grad(rho)|": {
        "label": "|\\nabla \\rho|",
        "units": "m^{-1}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "|grad(theta)|": {
        "label": "|\\nabla \\theta|",
        "units": "m^{-1}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "|grad(zeta)|": {
        "label": "|\\nabla \\zeta|",
        "units": "m^{-1}",
        "fun": "compute_contravariant_metric_coefficients",
        "dim": 1,
        "R_derivs": [[0, 0, 0]],
        "Z_derivs": [[0, 0, 0]],
    },
    # contravariant magnetic field
    "B0": {
        "label": "\\psi' / \\sqrt{g}",
        "units": "T m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0]],
    },
    "B^rho": {
        "label": "B^{\\rho}",
        "units": "T m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0]],
        "Z_derivs": [[0, 0, 0]],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta": {
        "label": "B^{\\theta}",
        "units": "T m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 0, 1]],
    },
    "B^zeta": {
        "label": "B^{\\zeta}",
        "units": "T m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0]],
    },
    "B": {
        "label": "\\mathbf{B}",
        "units": "T",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 3,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "B0_r": {
        "label": "\\psi'' / \\sqrt{g} - \\psi' \\partial_{\\rho} \\sqrt{g} / g",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta_r": {
        "label": "\\partial_{\\rho} B^{\\theta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 0, 1], [1, 0, 1]],
    },
    "B^zeta_r": {
        "label": "\\partial_{\\rho} B^{\\zeta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [1, 1, 0]],
    },
    "B_r": {
        "label": "\\partial_{\\rho} \\mathbf{B}",
        "units": "T",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 1], [1, 1, 0]],
    },
    "B0_t": {
        "label": "-\\psi' \\partial_{\\theta} \\sqrt{g} / g",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta_t": {
        "label": "\\partial_{\\theta} B^{\\theta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 0, 1], [0, 1, 1]],
    },
    "B^zeta_t": {
        "label": "\\partial_{\\theta} B^{\\zeta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 2, 0]],
    },
    "B_t": {
        "label": "\\partial_{\\theta} \\mathbf{B}",
        "units": "T",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 1, 1]],
    },
    "B0_z": {
        "label": "-\\psi' \\partial_{\\zeta} \\sqrt{g} / g",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta_z": {
        "label": "\\partial_{\\zeta} B^{\\theta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 0, 1], [0, 0, 2]],
    },
    "B^zeta_z": {
        "label": "\\partial_{\\zeta} B^{\\zeta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 1, 1]],
    },
    "B_z": {
        "label": "\\partial_{\\zeta} \\mathbf{B}",
        "units": "T",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1]],
    },
    "B0_tt": {
        "label": "-\\psi' \\partial_{\\theta\\theta} \\sqrt{g} / g + "
        + "2 \\psi' (\\partial_{\\theta} \\sqrt{g})^2 / (\\sqrt{g})^{3}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta_tt": {
        "label": "\\partial_{\\theta\\theta} B^{\\theta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 0, 1], [0, 1, 1], [0, 2, 1]],
    },
    "B^zeta_tt": {
        "label": "\\partial_{\\theta\\theta} B^{\\zeta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 2, 0], [0, 3, 0]],
    },
    "B0_zz": {
        "label": "-\\psi' \\partial_{\\zeta\\zeta} \\sqrt{g} / g + "
        + "2 \\psi' (\\partial_{\\zeta} \\sqrt{g})^2 / (\\sqrt{g})^{3}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta_zz": {
        "label": "\\partial_{\\zeta\\zeta} B^{\\theta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "L_derivs": [[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 0, 3]],
    },
    "B^zeta_zz": {
        "label": "\\partial_{\\zeta\\zeta} B^{\\zeta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 1, 1], [0, 1, 2]],
    },
    "B0_tz": {
        "label": "-\\psi' \\partial_{\\theta\\zeta} \\sqrt{g} / g + "
        + "2 \\psi' \\partial_{\\theta} \\sqrt{g} \\partial_{\\zeta} \\sqrt{g} / "
        + "(\\sqrt{g})^{3}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [[0, 0, 0]],
    },
    "B^theta_tz": {
        "label": "\\partial_{\\theta\\zeta} B^{\\theta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1], [0, 1, 2]],
    },
    "B^zeta_tz": {
        "label": "\\partial_{\\theta\\zeta} B^{\\zeta}",
        "units": "T \\cdot m^{-1}",
        "fun": "compute_contravariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 2, 0], [0, 1, 1], [0, 2, 1]],
    },
    # covariant magnetic field
    "B_rho": {
        "label": "B_{\\rho}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "B_theta": {
        "label": "B_{\\theta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "B_zeta": {
        "label": "B_{\\zeta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "B_rho_r": {
        "label": "\\partial_{\\rho} B_{\\rho}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]],
    },
    "B_theta_r": {
        "label": "\\partial_{\\rho} B_{\\theta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]],
    },
    "B_zeta_r": {
        "label": "\\partial_{\\rho} B_{\\zeta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]],
    },
    "B_rho_t": {
        "label": "\\partial_{\\theta} B_{\\rho}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 1, 1]],
    },
    "B_theta_t": {
        "label": "\\partial_{\\theta} B_{\\theta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 1, 1]],
    },
    "B_zeta_t": {
        "label": "\\partial_{\\theta} B_{\\zeta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 1, 1]],
    },
    "B_rho_z": {
        "label": "\\partial_{\\zeta} B_{\\rho}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1]],
    },
    "B_theta_z": {
        "label": "\\partial_{\\zeta} B_{\\theta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1]],
    },
    "B_zeta_z": {
        "label": "\\partial_{\\zeta} B_{\\zeta}",
        "units": "T \\cdot m",
        "fun": "compute_covariant_magnetic_field",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1]],
    },
    # magnetic field magnitude
    "|B|": {
        "label": "|\\mathbf{B}|",
        "units": "T",
        "fun": "compute_magnetic_field_magnitude",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "|B|_t": {
        "label": "\\partial_{\\theta} |\\mathbf{B}|",
        "units": "T",
        "fun": "compute_magnetic_field_magnitude",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 1, 1]],
    },
    "|B|_z": {
        "label": "\\partial_{\\zeta} |\\mathbf{B}|",
        "units": "T",
        "fun": "compute_magnetic_field_magnitude",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1]],
    },
    "|B|_tt": {
        "label": "\\partial_{\\theta\\theta} |\\mathbf{B}|",
        "units": "T",
        "fun": "compute_magnetic_field_magnitude",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 1, 1],
            [0, 3, 0],
            [0, 2, 1],
        ],
    },
    "|B|_zz": {
        "label": "\\partial_{\\zeta\\zeta} |\\mathbf{B}|",
        "units": "T",
        "fun": "compute_magnetic_field_magnitude",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 0, 2],
            [0, 1, 2],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [0, 1, 1],
            [0, 0, 3],
            [0, 1, 2],
        ],
    },
    "|B|_tz": {
        "label": "\\partial_{\\theta\\zeta} |\\mathbf{B}|",
        "units": "T",
        "fun": "compute_magnetic_field_magnitude",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [0, 1, 1],
            [0, 2, 1],
            [0, 1, 2],
        ],
    },
    # magnetic pressure gradient
    "grad(|B|^2)_rho": {
        "label": "(\\nabla B^{2})_{\\rho}",
        "units": "T^{2}",
        "fun": "compute_magnetic_pressure_gradient",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [1, 1, 0],
            [1, 0, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [2, 0, 0], [1, 1, 0], [1, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]],
    },
    "grad(|B|^2)_theta": {
        "label": "(\\nabla B^{2})_{\\theta}",
        "units": "T^{2}",
        "fun": "compute_magnetic_pressure_gradient",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [1, 1, 0], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 1, 1]],
    },
    "grad(|B|^2)_zeta": {
        "label": "(\\nabla B^{2})_{\\zeta}",
        "units": "T^{2}",
        "fun": "compute_magnetic_pressure_gradient",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [1, 0, 1], [0, 1, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 2], [0, 1, 1]],
    },
    "grad(|B|^2)": {
        "label": "\\nabla B^{2}",
        "units": "T^{2} \\cdot m^{-1}",
        "fun": "compute_magnetic_pressure_gradient",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "|grad(|B|^2)|": {
        "label": "\\nabla B^{2}",
        "units": "T^{2} \\cdot m^{-1}",
        "fun": "compute_magnetic_pressure_gradient",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    # magnetic tension
    "(curl(B)xB)_rho": {
        "label": "((\\nabla \\times \\mathbf{B}) \\times \\mathbf{B})_{\\rho}",
        "units": "T^{2}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "(curl(B)xB)_theta": {
        "label": "((\\nabla \\times \\mathbf{B}) \\times \\mathbf{B})_{\\theta}",
        "units": "T^{2}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "(curl(B)xB)_zeta": {
        "label": "((\\nabla \\times \\mathbf{B}) \\times \\mathbf{B})_{\\zeta}",
        "units": "T^{2}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "curl(B)xB": {
        "label": "(\\nabla \\times \\mathbf{B}) \\times \\mathbf{B}",
        "units": "T^{2} \\cdot m^{-1}",
        "fun": "compute_magnetic_tension",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "(B*grad)B": {
        "label": "(\\mathbf{B} \\cdot \\nabla) \\mathbf{B}",
        "units": "T^{2} \\cdot m^{-1}",
        "fun": "compute_magnetic_tension",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "((B*grad)B)_rho": {
        "label": "((\\mathbf{B} \\cdot \\nabla) \\mathbf{B})_{\\rho}",
        "units": "T^{2}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "((B*grad)B)_theta": {
        "label": "((\\mathbf{B} \\cdot \\nabla) \\mathbf{B})_{\\theta}",
        "units": "T^{2}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "((B*grad)B)_zeta": {
        "label": "((\\mathbf{B} \\cdot \\nabla) \\mathbf{B})_{\\zeta}",
        "units": "T^{2}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "|(B*grad)B|": {
        "label": "|(\\mathbf{B} \\cdot \\nabla) \\mathbf{B}|",
        "units": "T^2 \\cdot m^{-1}",
        "fun": "compute_magnetic_tension",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    # B dot grad(B)
    "B*grad(|B|)": {
        "label": "\\mathbf{B} \\cdot \\nabla B",
        "units": "T^2 \\cdot m^{-1}",
        "fun": "compute_B_dot_gradB",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "(B*grad(|B|))_t": {
        "label": "\\partial_{\\theta} (\\mathbf{B} \\cdot \\nabla B)",
        "units": "T^2 \\cdot m^{-1}",
        "fun": "compute_B_dot_gradB",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 3, 0],
            [1, 2, 0],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [0, 1, 1],
            [0, 3, 0],
            [0, 2, 1],
            [0, 1, 2],
        ],
    },
    "(B*grad(|B|))_z": {
        "label": "\\partial_{\\zeta} (\\mathbf{B} \\cdot \\nabla B)",
        "units": "T^2 \\cdot m^{-1}",
        "fun": "compute_B_dot_gradB",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 2, 0],
            [1, 0, 2],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 0, 3],
            [1, 2, 0],
            [1, 0, 2],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [0, 1, 1],
            [0, 0, 3],
            [0, 2, 1],
            [0, 1, 2],
        ],
    },
    # contravarian current density
    "J^rho": {
        "label": "J^{\\rho}",
        "units": "A \\cdot m^{-3}",
        "fun": "compute_contravariant_current_density",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "J^theta": {
        "label": "J^{\\theta}",
        "units": "A \\cdot m^{-3}",
        "fun": "compute_contravariant_current_density",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "J^zeta": {
        "label": "J^{\\zeta}",
        "units": "A \\cdot m^{-3}",
        "fun": "compute_contravariant_current_density",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "J": {
        "label": "\\mathbf{J}",
        "units": "A \\cdot m^{-2}",
        "fun": "compute_contravariant_current_density",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    # force error
    "F_rho": {
        "label": "F_{\\rho}",
        "units": "N \\cdot m^{-2}",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "F_theta": {
        "label": "F_{\\theta}",
        "units": "N \\cdot m^{-2}",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "F_zeta": {
        "label": "F_{\\zeta}",
        "units": "N \\cdot m^{-2}",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "F_beta": {
        "label": "F_{\\beta}",
        "units": "A",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "F": {
        "label": "\\mathbf{J} \\times \\mathbf{B} - \\nabla p",
        "units": "N \\cdot m^{-3}",
        "fun": "compute_force_error",
        "dim": 3,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "|F|": {
        "label": "|\\mathbf{J} \\times \\mathbf{B} - \\nabla p|",
        "units": "N \\cdot m^{-3}",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [2, 0, 0],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
    },
    "|grad(p)|": {
        "label": "|\\nabla p|",
        "units": "N \\cdot m^{-3}",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0]],
    },
    "|beta|": {
        "label": "|B^{\\theta} \\nabla \\zeta - B^{\\zeta} \\nabla \\theta|",
        "units": "T \\cdot m^{-2}",
        "fun": "compute_force_error",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    # quasi-symmetry
    "I": {
        "label": "I",
        "units": "T \\cdot m",
        "fun": "compute_quasisymmetry_error",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "G": {
        "label": "G",
        "units": "T \\cdot m",
        "fun": "compute_quasisymmetry_error",
        "dim": 1,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "QS_FF": {
        "label": "(\\mathbf{B} \\times \\nabla \\psi) \\cdot \\nabla B - "
        + "(M G + N I) / (M \\iota - N) \\mathbf{B} \\cdot \\nabla B",
        "units": "T^{3}",
        "fun": "compute_quasisymmetry_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
        ],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1], [0, 2, 0], [0, 0, 2], [0, 1, 1]],
    },
    "QS_TP": {
        "label": "\\nabla \\psi \\times \\nabla B \\cdot \\nabla "
        + "(\\mathbf{B} \\cdot \\nabla B)",
        "units": "T^{4} \\cdot m^{-2}",
        "fun": "compute_quasisymmetry_error",
        "dim": 1,
        "R_derivs": [
            [0, 0, 0],
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 3, 0],
            [0, 0, 3],
            [1, 2, 0],
            [1, 0, 2],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "Z_derivs": [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [1, 1, 0],
            [1, 0, 1],
            [0, 1, 1],
            [0, 3, 0],
            [0, 0, 3],
            [1, 2, 0],
            [1, 0, 2],
            [0, 2, 1],
            [0, 1, 2],
            [1, 1, 1],
        ],
        "L_derivs": [
            [0, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
            [0, 2, 0],
            [0, 0, 2],
            [0, 1, 1],
            [0, 3, 0],
            [0, 0, 3],
            [0, 2, 1],
            [0, 1, 2],
        ],
    },
    # energy
    "W": {
        "label": "W",
        "units": "J",
        "fun": "compute_energy",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "W_B": {
        "label": "W_B",
        "units": "J",
        "fun": "compute_energy",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "W_p": {
        "label": "W_p",
        "units": "J",
        "fun": "compute_energy",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "L_derivs": [[0, 0, 0]],
    },
    # geometry
    "V": {
        "label": "V",
        "units": "m^{3}",
        "fun": "compute_geometry",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "A": {
        "label": "A",
        "units": "m^{2}",
        "fun": "compute_geometry",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "R0": {
        "label": "R_{0}",
        "units": "m",
        "fun": "compute_geometry",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "a": {
        "label": "a",
        "units": "m",
        "fun": "compute_geometry",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
    "R0/a": {
        "label": "R_{0} / a",
        "units": "",
        "fun": "compute_geometry",
        "dim": 0,
        "R_derivs": [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
        "Z_derivs": [[1, 0, 0], [0, 1, 0], [0, 0, 1]],
    },
}
