#!/bin/bash
#SBATCH --job-name=cpu_35dip_RQA         # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem-per-cpu=500G         # memory per cpu-core (4G is default)
#SBATCH --time=30:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mail-type=begin        # send email when job begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu

module load anaconda3/2023.9
conda activate desc-env

jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace direct-reg.ipynb
