name: Unit tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        combos: [{group: 1, python_version: '3.9'}, {group: 2, python_version: '3.10'}, {group: 3, python_version: '3.11'}, {group: 4, python_version: '3.12'}]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.combos.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.combos.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devtools/dev-requirements.txt
          pip install matplotlib==3.7.2
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Test with pytest
        run: |
          pwd
          lscpu
          python -m pytest -v -m unit --durations=0 --cov-report xml:cov.xml --cov-config=setup.cfg --cov=desc/ --mpl --mpl-results-path=mpl_results.html --mpl-generate-summary=html --splits 4 --group ${{ matrix.combos.group }} --splitting-algorithm least_duration --db ./prof.db
      - name: save coverage file and plot comparison results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_artifact-${{ matrix.combos.python_version }}-${{ matrix.combos.group }}
          path: |
            ./cov.xml
            ./mpl_results.html
            ./prof.db
      - name: Upload coverage
        id : codecov
        uses: Wandalen/wretry.action@v1.3.0
        with:
          action: codecov/codecov-action@v3
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            files: ./cov.xml
            fail_ci_if_error: true
            verbose: true
          attempt_limit: 10
          attempt_delay: 60000 # ms, 1 min
