name: Cache dependencies
# This workflow is triggered every 2 days and updates the Python
# and pip dependencies cache
on:
  schedule:
    - cron: '30 8 */2 * *'  # This triggers the workflow at 4:30 AM ET every 2 days
    # cron syntax uses UTC time, so 4:30 AM ET is 8:30 AM UTC (for daylight time)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        combos:
          - {python_version: '3.9', venv_suffix: '9'}
          - {python_version: '3.10', venv_suffix: '10'}
          - {python_version: '3.11.11', venv_suffix: '11'}
          - {python_version: '3.12.8', venv_suffix: '12'}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.combos.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.combos.python_version }}

      - name: Delete old cached file with same python version
        run: |
          echo "Current Cached files list"
          gh cache list
          echo "Deleting cached files with pattern: ${{ runner.os }}-venv-${{ matrix.combos.venv_suffix }}-"
          for cache_key in $(gh cache list --json key -q ".[] | select(.key | startswith(\"${{ runner.os }}-venv-${{ matrix.combos.venv_suffix }}-\")) | .key"); do
            echo "Deleting cache with key: $cache_key"
            gh cache delete "$cache_key"
          done

      # Update the matplotlib version if needed later
      - name: Set up virtual environment
        run: |
          python -m venv .venv-${{ matrix.combos.venv_suffix }}
          source .venv-${{ matrix.combos.venv_suffix }}/bin/activate
          python -m pip install --upgrade pip
          pip install -r devtools/dev-requirements.txt
          pip install matplotlib==3.9.2

      - name: Cache Python environment
        id: cache-env
        uses: actions/cache@v4
        with:
          path: .venv-${{ matrix.combos.venv_suffix }}
          key: ${{ runner.os }}-venv-${{ matrix.combos.venv_suffix }}-${{ hashFiles('devtools/dev-requirements.txt', 'requirements.txt') }}

      - name: Verify virtual environment activation
        run: |
          source .venv-${{ matrix.combos.venv_suffix }}/bin/activate
          which python
          python --version
          pip --version
          pip list
