name: Check changelog updated

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  get_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.step1.outputs.labels }}
    steps:
      - id: step1
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          echo "$labels"
          echo "$labels" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  check_changelog_updated:
    runs-on: ubuntu-latest
    needs: get_labels
    if: contains(${{needs.get_labels.outputs.labels}}, 'skip_changelog') == false
    steps:
      - uses: actions/checkout@v4
      - uses: danieljimeneznz/ensure-files-changed@v4.1.0
        with:
          require-changes-to: |
            CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
