name: Check changelog updated

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check_changelog_updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip_changelog') }}
        uses: danieljimeneznz/ensure-files-changed@v4.1.0
        with:
          require-changes-to: |
            CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
