name: tests

on: 
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devtools/dev-requirements.txt
      - name: Test with pytest
        run: |
          pwd
          lscpu
          python -m pytest --durations=0 --cov-report xml:cov.xml --cov-config=setup.cfg --cov=desc/ --mpl
      - name: save coverage file
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./cov.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella # optional
          files: ./cov.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

