name: Weekly tests

on:
  schedule:
      - cron: '17 9 * * 1'
  workflow_dispatch:

jobs:
  unit_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        combos: [{group: 1, python_version: '3.8'}, {group: 2, python_version: '3.9'}, {group: 3, python_version: '3.10'}, {group: 4, python_version: '3.11'}, {group: 5, python_version: '3.12'}]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.combos.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.combos.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devtools/dev-requirements.txt
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Test with pytest
        run: |
          pwd
          lscpu
          python -m pytest -v -m unit --durations=0 --splits 5 --group ${{ matrix.combos.group }} --splitting-algorithm least_duration
