#!/bin/bash
#SBATCH --job-name=rd_RQA          # create a short name for your job
#SBATCH --time=01:00:00          # total run time limit (HH:MM:SS)
#SBATCH --mem=80G
#SBATCH --mail-type=begin        # send mail when process begins
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=fcastro@princeton.edu
#SBATCH --constraint=gpu80
#SBATCH --gres=gpu:1

module load anaconda3/2023.9
conda activate desc-env
export XLA_PYTHON_CLIENT_MEM_FRACTION=.93

jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute --inplace direct-reg.ipynb
